name: todo_app

description: "A simple to do app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  floor:
  provider:
  font_awesome_flutter:
  sqflite:
  lottie:
  fluttertoast:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  floor_generator:
  build_runner:

flutter:

  uses-material-design: true
  # ASSETS
  assets:
    - assets/anims/

  # SANS FONT
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf

    - family: SansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf



